title: "[Bug Discussion]"

labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        **What’s the problem?**  
        _Explain the problem clearly. What’s going wrong or not working?_
  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Detailed steps to reproduce the behavior, so that it can be easily diagnosed."
      placeholder: |
        1. _What was the first thing you did?_
        2. _What did you do next?_
        3. _What happened after that?_
        4. _Keep adding steps until we know exactly how to reproduce the problem._
        ...

        _The more clear the steps, the easier it is for us to understand!_
      render: bash
      validations:
        required: true
