name: Create Branch on Issue Status Update

on:
  issues:
    types:
      - labeled
      - edited
      - opened
      - closed

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the issue details
        id: issue_details
        run: |
          # Fetch the issue details from the event payload
          echo "ISSUE_URL=${{ github.event.issue.url }}" >> $GITHUB_ENV
          echo "ISSUE_ID=${{ github.event.issue.id }}" >> $GITHUB_ENV

      - name: Get linked project and column
        id: project_column
        run: |
          # Use GitHub API to get the projects linked to the issue
          response=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            "$ISSUE_URL/projects")
          # Parse out the project and column details
          project_column=$(echo "$response" | jq -r '.[0].column_url' || echo "No Project")
          
          if [[ "$project_column" == "No Project" ]]; then
            echo "No project linked to this issue. Skipping branch creation."
            echo "create_branch=false" >> $GITHUB_ENV
          else
            # Retrieve the project column's status
            column_name=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                               -H "Accept: application/vnd.github.v3+json" \
                               "$project_column" | jq -r '.name')
            echo "Column name: $column_name"

            # Check if the column name is 'In Progress'
            if [[ "$column_name" == "In Progress" ]]; then
              echo "This issue is now 'In Progress'. Proceeding to create a branch."
              echo "create_branch=true" >> $GITHUB_ENV
            else
              echo "Column is not 'In Progress'. Skipping branch creation."
              echo "create_branch=false" >> $GITHUB_ENV
            fi
          fi

      - name: Create a new branch if it doesn't exist
        if: env.create_branch == 'true'
        run: |
          # Get the issue title and sanitize to create a branch name
          issue_title=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                              -H "Accept: application/vnd.github.v3+json" \
                              ${{ env.ISSUE_URL }} | jq -r '.title')
          branch_name=$(echo "issue-${issue_title}" | sed 's/[^a-zA-Z0-9]/-/g')

          echo "Branch name: $branch_name"

          # Check if the branch already exists
          existing_branch=$(git branch -r | grep "origin/$branch_name")

          if [[ -z "$existing_branch" ]]; then
            echo "Branch does not exist. Creating branch: $branch_name"
            # Create the branch from the main branch
            git checkout -b $branch_name
            git push origin $branch_name
          else
            echo "Branch $branch_name already exists. Skipping branch creation."
          fi
