name: Frontend Test, Build and Deploy
on:
    push:
        branches:
            - deploy
jobs:
    Test_Build_and_Deploy:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: Project/client        

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'  

            - name: Install dependicies
              run: npm install 

            - name: Use Node.js to test 
              uses: actions/setup-node@v4
              with:
                cache: 'npm'
                cache-dependency-path: Project/client/package-lock.json
            - run: npm test

            - name: Build React app
              run: | 
                npm run build
                ls
                ls -la dist

            # Set up Docker
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            # Build Docker image for Nginx to serve the React app
            - name: Build Docker image
              run: |
                docker build -t frontendapp ./ # Make sure you have a Dockerfile in the root
                cd ./dist
                ls

            # Save the Docker image as a tarball file
            - name: Save Docker image to tarball
              run: |
                docker save frontendapp -o frontendapp.tar
                cd ..
                find ./ -name frontendapp.tar
                
            - name: Copy Docker image to remote server
              uses: appleboy/scp-action@v0.1.0
              with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.REMOTE_USER }}
                key: ${{ secrets.REMOTE_PASSWORD }}
                passphrase: ${{ secrets.SSH_PASSPHRASE }}
                port: 22
                source: "/home/runner/work/ExamProjectSoft2ndSem/ExamProjectSoft2ndSem/Project/client/frontendapp.tar"
                target: "../app"    

            - name: Deploy Docker image on remote server
              uses: appleboy/ssh-action@v0.1.5
              with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.REMOTE_USER }}
                key: ${{ secrets.REMOTE_PASSWORD }}
                passphrase: ${{ secrets.SSH_PASSPHRASE }}
                port: 22
                script: |
                  cd ../app/github/workspace/Project/client
                  
                  ls -lh frontendapp.tar

                  # Load the Docker image from the tarball
                  docker load -i frontendapp.tar

                  docker build -t frontendapp

                  # Stop and remove any running container (optional)
                  docker stop frontendapp || true
                  docker rm frontendapp || true

                  # Run the new container
                  docker run -it -d --name frontendapp -p 3001:3001 frontendapp    

                  docker start frontendapp