name: Frontend Test, Build and Deploy
on:
    push:
        branches:
            - deploy
jobs:
    Test_Build_and_Deploy:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: Project/client        

        steps:
            - name: checkout
              uses: actions/checkout@v2
            
            - name: Use Node.js to test 
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
                cache: 'npm'
                cache-dependency-path: Project/client/package-lock.json
            - run: npm install
            - run: npm test
