name: Backend Test, Build and Deploy
on:
    push:
        branches:
            - deploy
jobs:
    Test_Build_and_Deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['18.x','20.x']

        steps:
            - name: checkout
              uses: actions/checkout@v2
            
            - name: Use Node.js ${{ matrix.node-version}} to test 
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}
                cache: 'npm'
                working-directory: Project/client 
            - run: npm install
              working-directory: Project/client 
            - run: npm test
              working-directory: Project/api  